spring.application.name=ProductCatalog

#Server Port
server.port=8080

#MYSQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/product_catalog

spring.datasource.username = root
spring.datasource.password = 2002

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate config
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true